# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/resources/brave_grit.gni")

assert(is_desktop_linux || is_win || is_mac)

brave_grit("static_resources") {
  source = "crekk_mirror_resources.grd"

  outputs = [
    "grit/crekk_mirror_resources.h",
    "crekk_mirror_static.pak",
  ]
}
